### PR TITLE
Added Coinbase Wallet via walletlink

### PR DESCRIPTION
**Pull request by mwdwrd**

### CODE REVIEW

**Comment by mwdwrd** [comment]
Added WalletLink as a provider – https://www.walletlink.org/#/

**Comment by mikedeshazer** [comment]
Are the conflicts the only thing wrong in this pr?

**Comment by crisgarner** [comment]
Not sure @mikedeshazer, I'll check it out this week to see if it's something easy to fix

**Comment by waterdrop01** [comment]
Hello @mwdwrd, has your PR been merged?

@pedrouid Many users are now asking for Coinbase wallet support. Any chance to have a look at this PR? 

Thanks a lot :)

**Comment by sa1i** [comment]
@pedrouid any udpates?

**Comment by mwdwrd** [comment]
My linter created a whoooole bunch of conflicts for this PR...
Hopefully I'll have some time to look at it tomorrow.

>

**Comment by Thrasymachus01** [comment]
What is the status on this?

**Comment by ilake** [comment]
any updated?

**Comment by ilake** [comment]
hi, @pedrouid any updates? thanks

**Pull request closed without merging**
