### PR TITLE
v1.0.0-beta.26

### PR DESCRIPTION
**Pull request by pedrouid**
- deprecate individual connectors
- updated README for readability
- expose instantiated libraries
- cache preferred provider in localStorage
- update dependencies in example

### CODE REVIEW

**Comment by pedrouid** [comment]
Fix #68 
Fix #102

**Comment by pedrouid** [comment]
the build error is probably related to some dependency upgrade on the example app

**Comment by pedrouid** [comment]
We need to discuss the cache preferred provider cc @crisgarner 

Currently all versions until 1.0.0-beta.25 did NOT cache the user's preferred provider by default

So we should probably disable it by default to make it backwards compatible and document it for developers to enable themselves

**Comment by crisgarner** [comment]
> We need to discuss the cache preferred provider cc @crisgarner
> 
> Currently all versions until 1.0.0-beta.25 did NOT cache the user's preferred provider by default
> 
> So we should probably disable it by default to make it backwards compatible and document it for developers to enable themselves

Sure, I don't think it will be a problem since a lot of devs have been asking for this, but it makes sense for people that just update libraries and don't read the docs.  Do we need a way to delete the session? It might be helpful to create some sort of sign-in / sign out. :thinking:

**Comment by pedrouid** [comment]
Maybe we should cut a release with everything except the preferred provider stuff for now

**Comment by pedrouid** [comment]
Replaced by #106

**Pull request closed without merging**
