### PR TITLE
Torus Integration with web3Connect

### PR DESCRIPTION
**Pull request by YZhenY**
Torus integration to web3Connect. PR includes:
- Added provider/connector
- Included logo
- Tested with ```npm pack```
- Added Torus to readme
- Adjusted webpack versioning for ```npm link```

### CODE REVIEW

**Comment by crisgarner** [comment]
hey @YZhenY  I'm testing this at the moment, but can't get to run tours on the example. I'm adding  ``torus: {}`` to the list of providers but nothing happens

**Comment by YZhenY** [comment]
yo @crisgarner, with the examples, the master branch doesn't pop up the model. i didnt have the time to dive into why, perhaps i could get some help there

 if you ```npm pack``` this branch and install it on a blank app it works as intended

**Comment by crisgarner** [comment]
Hey @YZhenY it works fine! there is just an issue when you hit disconnect, Torus keeps connected.

**Comment by YZhenY** [comment]
Thanks for checking up @crisgarner - facing an issue with utilizing the ```Torus``` object with the logout function. Whilst we can include the logout feature on the provider, do you think we could find some way to expose the functions somehow other than tossing it on the provider?

For example, Torus provides an email resolver to public keys for dapps to use via its object. Would love to expose this

**Comment by pedrouid** [comment]
This PR should wait for the refactor on #79

**Comment by YZhenY** [comment]
sure that makes sense @pedrouid and @crisgarner, whats the timeline to getting them merged

**Comment by pedrouid** [comment]
Hi @YZhenY, I merged it yesterday and already published it with release beta.22.

**Comment by lukasschor** [comment]
I recommend using a PNG of the Google icon as it looks better in hover state.

Screenshot 2019-09-16 at 11 20 02

Also I find the wording confusing. I would just say "Google" as the main title and then use "Connect to (/with) your Google account via (/using) Torus" as a subtitle.

**Comment by pedrouid** [comment]
I agree with @lukasschor feedback, also @YZhenY wouldn't it be possible to allow Torus integration to have multiple social logins. Why does it need to be "via Google"? Couldn't we provide a Torus integration which then displays an option to select different social logins?

**Comment by YZhenY** [comment]
thanks for the feedback @lukasschor @pedrouid. We'd always go for the most intuitive copywriting, I've also adjusted the png.

With regards to multiple logins @pedrouid, it is possible to support additional logins, but the flows aren't implemented in production just yet. Will adjust the integration when it is. 

Since #65 isn't merged yet, I've defaulted the UI to be hidden through web connect. Once it is we can utilize the cleanup flow on the torus object.

Let me know anything else I can do @pedrouid @crisgarner to get this merged. Have people keen to use Web3Connect and Torus!

**Comment by YZhenY** [comment]
Any updates here guys? Keen to push this forward

**Comment by YZhenY** [comment]
@crisgarner @pedrouid

**Comment by crisgarner** [comment]
@YZhenY tested everything and works fine! Thanks, merged now

**Comment by hainusii** [comment]
> Torus integration to web3Connect. PR includes:
> 
> * Added provider/connector
> * Included logo
> * Tested with `npm pack`
> * Added Torus to readme
> * Adjusted webpack versioning for `npm link`

**Pull request merged**
